#!/usr/bin/ruby
require 'optparse'

outjpg = '/tmp/outjpg.out'
outdir = '/home/mike/public_html/'

options = {:resize => '640x480' }

OptionParser.new do |opts|
  opts.banner = "Usage: jpg2mp4 [options]"

  opts.on("-v", "--verbose", "verbose") do |v|
    options[:verbose] = v;
  end
  opts.on("-oName", "--out=Name", "output the mp4 to specified file") do |o|
    options[:output] = o
  end
  opts.on("-rName", "--resize=Name", "resize to geometry -rXXXxYYY") do |r|
    options[:resize] = r
  end  
  opts.on("-D", "--[no-]dry", "Dry run (don't change anything") do |d|
    options[:dry] = true
  end
end.parse!

puts options if options[:verbose]

Dir.chdir "/home/camuser"
dir = ARGV[0]
ofile = File.basename dir
if options[:output]
  outmp4 = options[:output]
else
  outmp4 = outdir + ofile + '.mp4'
end

files = (`find #{dir} -type f -name '*.jpg' |sort`).split "\n"

begin
  File.delete outjpg
rescue
end

puts "process #{files.length} jpgs" if options[:verbose]
i = 1
tottime = 0.0
files.each do |file|
  s = File.size(file) / 1000
  time = (`time -f '%e'  2>&1 convert #{file} -scale #{options[:resize]} JPG:- >>#{outjpg}`).strip
  puts "#{i}/#{files.length} #{file} (#{s}k #{time}s)" if options[:verbose]
  tottime += time.to_f
  i += 1
end
puts "elapsed time for convert: #{tottime}s" if options[:verbose]
puts "ffmpeg..." if options[:verbose]
cmd = "cat #{outjpg} | ffmpeg -y -framerate 10 -f image2pipe -i - -vf scale=#{options[:resize]} -c:v libx264 -r 30 -pix_fmt yuv420p #{outmp4}"
cmd = cmd + ' 2>/dev/null' if not options[:verbose]
puts cmd if options[:verbose]
system(cmd) unless options[:dry]

begin
  File.delete outjpg
rescue
end
